name: Frontend CD

on:
  workflow_run:
    workflows: 
      - Backend app CI
    types:
      - completed

env:
  APP_NAME: ${{ secrets.AZURE_JAVA_APP_NAME }}
  PUBLISH_PROFILE: ${{ secrets.AZURE_JAVA_PUBLISH_PROFILE }}
  ARTIFACT_NAME: ${{ vars.BACKEND_ARTIFACT_NAME }}

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: target
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }} 
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          package: target/*.jar