name: Backend app CI
run-name: backend-ci

on:
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          
      - name: Install dependencies
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Build app
        run: mvn package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar