name: Backend CICD

on:
  push:
    branches:
      - master
    paths:
      - backend/**


env:
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  ARTIFACT_NAME: ${{ vars.BACKEND_ARTIFACT_NAME }}
  APP_NAME: ${{ secrets.AZURE_JAVA_APP_NAME }}
  PUBLISH_PROFILE: ${{ secrets.AZURE_JAVA_PUBLISH_PROFILE }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: temurin
      - name: Run tests
        run: mvn -B test
      - name: Build the app
        run: mvn package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./backend/target/*.jar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: target
      - name: Deploy App to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          package: target/*.jar