name: Cowsay CI

on:
  push:
    branches:
      - master
    paths:
      - cowsay/**


jobs:
  build-test:
    strategy:
      matrix:
        runners: [ubuntu-latest, windows-latest]
        node-version: [18, 16, 14]
    runs-on: ${{ matrix.runners }}
    defaults:
      run:
        working-directory: ./cowsay
    steps: 
      - name: Clone code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm # add later
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # - name: test # remove later
      #   run: npm run test
        