name: Cowsay CI

on:
  push:
    branches:
      - master
    paths:
      - cowsay/**


jobs:
  build-test:
    defaults:
      run:
        working-directory: ./cowsay

    strategy:
      matrix:
        runners: [ubuntu-latest, windows-latest]
        node-version: [20, 18, 16]

    runs-on: ${{ matrix.runners }}

    steps: 
      - name: Clone code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm # add later
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # - name: test # remove later
      #   run: npm run test
        