name: Deploy to Azure app service
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
      artifact-path:
        type: string
        required: true
      package:
        type: string
        required: true
    secrets:
      app-name:
        required: true
      publish-profile:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
      - name: Deploy App to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.app-name }}
          publish-profile: ${{ secrets.publish-profile }}
          package: ${{ inputs.package }}