name: Frontend 

on:
  push:
    branches:
      - master
    paths:
      - frontend/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: node:20


    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Clone code
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
          
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.FRONTEND_ARTIFACT_NAME }}
          path: ./frontend/dist 

  deploy:
    needs: build-and-test
    uses: ./.github/workflows/deploy_to_azure.yml
    with:
      artifact-name: ${{ vars.FRONTEND_ARTIFACT_NAME }}
      artifact-path: .
      package: .
    secrets:
      app-name: ${{ secrets.AZURE_REACT_APP_NAME }}
      publish-profile: ${{ secrets.AZURE_REACT_PUBLISH_PROFILE }}